## ██████╗░░█████╗░███╗░░██╗██████╗░░█████╗░░██████╗██╗░░██╗░█████╗░██████╗░##
## ██╔══██╗██╔══██╗████╗░██║██╔══██╗██╔══██╗██╔════╝██║░░██║██╔══██╗██╔══██╗##
## ██████╔╝███████║██╔██╗██║██║░░██║███████║╚█████╗░███████║██║░░██║██████╔╝##
## ██╔═══╝░██╔══██║██║╚████║██║░░██║██╔══██║░╚═══██╗██╔══██║██║░░██║██╔═══╝░##
## ██║░░░░░██║░░██║██║░╚███║██████╔╝██║░░██║██████╔╝██║░░██║╚█████╔╝██║░░░░░##
## ╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░╚═╝░░╚═╝╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░##
## ------------------------------------------------------------------------##
##                              Author: MrErrors                           ##
##                               Version: 1.0.1                            ##
## ------------------------------------------------------------------------##
# Welcome to Panda Shop thank you for downloading first off!!
# If you ever have any questions please feel freee to contact me in the discord
# All the main information will be available below for Main Menu of the shop and the shop layout.
Update-Checker: true
Verison: 1.0.1
Language: US_EN

